apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
  namespace: web-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: aakritdongol/backend-img:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        # MySQL Database Settings
        - name: DB_NAME
          value: "todoList"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "root"
        - name: DB_HOST
          value: "database-service.web-ns.svc.cluster.local"
        - name: DB_PORT
          value: "3306"
        volumeMounts:
        - mountPath: /app/backend/staticfiles
          name: static-files-volume
          readOnly: false  # Read-write access for backend
      volumes:
      - name: static-files-volume
        persistentVolumeClaim:
          claimName: static-pvc