apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pvc
  namespace: web-ns
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
